### PR TITLE
Migrate skin to Doxia 2.x

### PR DESCRIPTION
**Pull request by slawekjaranowski**

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
@garydgregory @michael-o 
I have tested with commons parent - one issue what I see is:

```
<title>About ? Apache Commons</title>
```
it is generated question mark

**Comment by michael-o** [comment]
> @garydgregory @michael-o I have tested with commons parent - one issue what I see is:
> 
> ```
> <title>About ? Apache Commons</title>
> ```
> 
> it is generated question mark

There is an encoding issue some where. ISO-8859-1 somewhere?

**Comment by slawekjaranowski** [comment]
> > @garydgregory @michael-o I have tested with commons parent - one issue what I see is:
> > ```
> > <title>About ? Apache Commons</title>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > it is generated question mark
> 
> There is an encoding issue some where. ISO-8859-1 somewhere?

There is: https://github.com/apache/commons-parent/blob/master/pom.xml#L278-L284

**Comment by michael-o** [comment]
> > > @garydgregory @michael-o I have tested with commons parent - one issue what I see is:
> > > ```
> > > <title>About ? Apache Commons</title>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it is generated question mark
> > 
> > 
> > There is an encoding issue some where. ISO-8859-1 somewhere?
> 
> There is: https://github.com/apache/commons-parent/blob/master/pom.xml#L278-L284
> 
> after change to `utf-8` it is ok 😄

For me, there is ZERO reason to stick to ISO-8859-X these days.

**Comment by garydgregory** [comment]
> > > @garydgregory @michael-o I have tested with commons parent - one issue what I see is:
> > > ```
> > > <title>About ? Apache Commons</title>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > it is generated question mark
> > 
> > 
> > There is an encoding issue some where. ISO-8859-1 somewhere?
> 
> There is: https://github.com/apache/commons-parent/blob/master/pom.xml#L278-L284
> 
> after change to `utf-8` it is ok 😄

I will make the change in commons parent and create a release candidate.

**Comment by garydgregory** [comment]
@slawekjaranowski 

Thank you so much for the PR! 

I just pushed commit https://github.com/apache/commons-parent/commit/1d943fad67255d84f38244c49034a667c143e116 to commons-parent. 

Would the simplest steps be:
- Set `commons.encoding` here (commons-skin) to `UTF-8`
- Release commons-skin 4.3
- In commons-parent, update from commons-skin 4.2 to 4.3 
- Release commons-parent 79
- Update other commons component, including commons-skin to commons-parent 79

?

**Comment by slawekjaranowski** [comment]
@garydgregory 
- commons-skin 4.3 - will require m-site-p 3.20.0+
- with m-site-p 3.20.0+ you will need a new version of m-changes-p
 
so first I would like to finish m-changes-p

**Comment by garydgregory** [comment]
@slawekjaranowski 

OK, TY, I might release a new commons-parent in the meantime, but we'll loop again when m-changes-p is released.

TY again 😄

**Comment by slawekjaranowski** [comment]
@garydgregory  m-changes-p was released we can process forward
I will check again parent if site is ok with this and new m-site-p

**Comment by garydgregory** [comment]
@slawekjaranowski 

Is this OK to merge and release now that maven-changes-plugin 3.0.0-M1 is available?

**Comment by slawekjaranowski** [comment]
there are tests:
 - https://github.com/apache/commons-parent/pull/561
 - https://github.com/apache/commons-validator/pull/298
 
@garydgregory site generation looks ok - please verify and we can go forward

**Comment by slawekjaranowski** [comment]
> @slawekjaranowski
> 
> Is this OK to merge and release now that maven-changes-plugin 3.0.0-M1 is available?

yes skin look ok

**Comment by garydgregory** [comment]
TY @slawekjaranowski 
I verified by building local changes to this, commons-parent, and validator.

**Pull request merged**
